<?xml version="1.0" encoding="utf-8"?><Database Name="CREATIVOS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=CREATIVOS;Persist Security Info=True;User ID=sa" SettingsObjectName="CREATIVOS.My.MySettings" SettingsPropertyName="CREATIVOSConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Baners" Member="Baners">
    <Type Name="Baners">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad_Letras" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Medidas" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tickets" Member="Tickets">
    <Type Name="Tickets">
      <Column Name="Ticket" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Clientes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Control_Recargas_Claro" Member="Control_Recargas_Claro">
    <Type Name="Control_Recargas_Claro">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Compra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Saldo_Anterior" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Saldo_Actual" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vendido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Efectivo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creditos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Errores" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cierre" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Control_Recargas_Tigo" Member="Control_Recargas_Tigo">
    <Type Name="Control_Recargas_Tigo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Compra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Saldo_Anterior" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Saldo_Actual" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Vendido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Efectivo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creditos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Errores" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cierre" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Deducciones" Member="Deducciones">
    <Type Name="Deducciones">
      <Column Name="Codigo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Descripcion" Member="Descripcion">
    <Type Name="Descripcion">
      <Column Name="Ticket" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Detalle" Member="Detalle">
    <Type Name="Detalle">
      <Column Name="Cotizacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empleados" Member="Empleados">
    <Type Name="Empleados">
      <Column Name="Codigo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Inventario" Member="Inventario">
    <Type Name="Inventario">
      <Column Name="Codigo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Login">
    <Type Name="Login">
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prestamos" Member="Prestamos">
    <Type Name="Prestamos">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Codigo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prestamo" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recibos" Member="Recibos">
    <Type Name="Recibos">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad_Letras" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Saldo_Anterior" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Abono" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Saldo_Actual" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recibos_Pendientes" Member="Recibos_Pendientes">
    <Type Name="Recibos_Pendientes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad_Letras" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Saldo_Anterior" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Abono" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Saldo_Actual" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Total" Member="Total">
    <Type Name="Total">
      <Column Name="Codigo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Total_Deduccion" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cotizaciones" Member="Cotizaciones">
    <Type Name="Cotizaciones">
      <Column Name="Cotizacion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Creditos_Recargas" Member="Creditos_Recargas">
    <Type Name="Creditos_Recargas">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>