<?xml version="1.0" encoding="utf-8"?><Database Name="OFICIALIA" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=OFICIALIA;Persist Security Info=True;User ID=sa" SettingsObjectName="Oficialia.My.MySettings" SettingsPropertyName="OFICIALIAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Seguridad" Member="Seguridad">
    <Type Name="Seguridad">
      <Column Name="Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Solicitudes" Member="Solicitudes">
    <Type Name="Solicitudes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Identidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expediente" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TGR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Solicitante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Persona_Inscrita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tipo_Solicitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Solicitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Resolucion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Envio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Remision" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Auto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Caja" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaRs" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaRm" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>