<?xml version="1.0" encoding="utf-8"?><Database Name="SystemLetona" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=SystemLetona;Persist Security Info=True;User ID=sa" SettingsObjectName="Sistema_Clinico.My.MySettings" SettingsPropertyName="SystemLetonaConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pacientes" Member="Pacientes">
    <Type Name="Pacientes">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Identidad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha_Nacimiento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Documentos" Member="Documentos">
    <Type Name="Documentos">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Documento" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Prescripcion" Member="Prescripcion">
    <Type Name="Prescripcion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Historia" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Medicacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Nota" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Calendario" Member="Calendario">
    <Type Name="Calendario">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Citas" Member="Citas">
    <Type Name="Citas">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Identidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Identidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Historial" Member="Historial">
    <Type Name="Historial">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo_Historial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Identidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Edad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Motivo_Consulta" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Antecedentes_Personales" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Antecedentes_Familiares" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="HEA" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Examen_Fisico" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Examenes_Complementarios" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="T" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Peso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diagnostico" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Tratamiento" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Historial_Historial" Member="Historial1" ThisKey="Id" OtherKey="Id" Type="Historial" Cardinality="One" />
      <Association Name="Historial_Historial" Member="Historial" ThisKey="Id" OtherKey="Id" Type="Historial" IsForeignKey="true" />
    </Type>
  </Table>
</Database>